### ISSUE TITLE
Add HTTPS to the oracle API

### ISSUE THREAD

**Issue by Marketen** [dappnode/mev-sp-oracle#107]
For security reasons, General Magic has requested that the API be served over HTTPS. A self-signed certificate will be sufficient. However, it is crucial to ensure proper implementation.

- Passphrase Protection: Should the certificate be protected with a passphrase?
- Deploying the Certificate and Key: How can we safely deploy the certificate and its key to the Oracle container without compromising any security measures?

**Comment by alrevuelta** [comment]
https will be implemented via nginx, so this is a deployment configuration, no change required in the oracle.
