### ISSUE TITLE
Change Oracle State from .gob to JSON

### ISSUE THREAD

**Issue by Marketen** [dappnode/mev-sp-oracle#122]
As a possible upgrade, we could consider changing the save state file from a .gob file to a JSON file, this would bring the following benefits:
- more human-readable
- easier to control/know which oracle state versions are not compatible with eachother
- easy to process it with a script and get stats from it

Possible downsides:
- state as JSON could not be the optimum to read for the oracle, may take longer to read a .json file than a .gob file.

**Comment by alrevuelta** [comment]
closed in https://github.com/dappnode/mev-sp-oracle/pull/134
