### ISSUE TITLE
Specify which client is out of sync

### ISSUE THREAD

**Issue by Marketen** [dappnode/mev-sp-oracle#130]
While executing, oracle checks frequently if EC or CC are not in sync. If any of them is not in sync, the log "Nodes are not in sync, skipping until in sync" is printed. This log is vague, and leaves the oracle operator wondering which client is misbehaving.

We should specify which client is out of sync, so the operator can see whats wrong quicker.

**Comment by alrevuelta** [comment]
done https://github.com/dappnode/mev-sp-oracle/pull/159
logs log.Info("Exec client not in sync")
or log.Info("Consensus client not in sync, Client is more than 5 slots behind")
