### ISSUE TITLE
Make oracle less strict with sync status.

### ISSUE THREAD

**Issue by Marketen** [dappnode/mev-sp-oracle#131]
Currently, oracle defines EC/CC clients being in sync if they are synced to latest head. While executing oracle on besu/prysm(archive), besu/lighthouse(archive), these clients may get out of sync during a few seconds once in a while, and oracle sees it:
![image](https://github.com/dappnode/mev-sp-oracle/assets/36164126/b4cfc594-e47c-4c6c-8d12-a919c7eb77e4)

This is a problem because oracle stops trying to advancestate if he decided that nodes are not in sync. Maybe we could make oracle less strict so that he defines sync by "last finalized" instead of "latest head"

**Comment by alrevuelta** [comment]
done https://github.com/dappnode/mev-sp-oracle/pull/159
