### ISSUE TITLE
Exiting validators without unsubscribing does not remove them from the pool

### ISSUE THREAD

**Issue by MrYukonC1** [dappnode/mev-sp-oracle#227]
**Describe the bug**

Exiting validators without first unsubscribing, results in the pool incorrectly thinking the validators are still subscribed -- the subscriber count does no go down to reflect the number of exited validators.

Additionally, this directly (negatively) affects the calculated awards for all remaining subscribed validators -- they are getting less because the pool is still accumulating awards to validators that are no longer subscribed or validating.

**To Reproduce**
1. subscribe to Smooth
2. exit validator without unsubscribing

**Expected behavior**

The oracle should correctly detect that subscribed validators have exited and then remove them from the pool.

**Comment by Marketen** [comment]
We're building the fix for this bug here: #226
