### ISSUE TITLE
Ensure the configured account updating the merkle root matches the contract

### ISSUE THREAD

**Issue by alrevuelta** [dappnode/mev-sp-oracle#81]
* The oracle is configured with a given account, provided as a password protected keystore that is used when submitting the merkle root update transaction.
* We must ensure that this account matches the contract `oracle` and ~~owner~~ addresses, otherwise when updating the contract it will fail due to permissions.
* This is of paramount importance, since if we dont do this check at startup, we won't notice of this missconfiguration issue until the tx is sent. Causing a crash that can be prevented.

**Comment by Marketen** [comment]
Is the configured oracle account the "UpdaterAddress" seen in config.go? In the configuration params, there are 3 related to the oracle account:https://github.com/dappnode/mev-sp-oracle/blob/848b3b20cd5c1ed634111f8327e1ce72341db4d4/config/config.go#L30-L32. 
I understand that they refer to pubkey, path of keystore and privkey stored in keystore. However, "UpdaterAddress" is not parsed at "NewCliConfig()" method in config.go: https://github.com/dappnode/mev-sp-oracle/blob/848b3b20cd5c1ed634111f8327e1ce72341db4d4/config/config.go#L62-L68. 

Ill implement the parsing and compare it with the `oracle` param of the smart contract onchain.

Also, wouldn't it be better to get both pub and privkey from the keystore?

**Comment by alrevuelta** [comment]
With multioracle, the whitelisted addresses are detected with events. Implemented here https://github.com/dappnode/mev-sp-oracle/blob/main/oracle/onchain.go#L371
